import {StyleSheet} from "react-native";


export const newStyles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        paddingHorizontal: 10,
        paddingTop: 50,
        paddingBottom: 20,
        alignItems: 'center',
    },
    flatListContainer: {
        alignItems: 'center',
    },
    paginationContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    paginationDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#ccc',
        marginHorizontal: 4,
    },
    paginationDotActive: {
        backgroundColor: '#000',
    },
    buttonsContainer: {
        marginTop: 20,
        width: '100%',
        alignItems: 'center',
        height: 80, 
    },
    previewImageContainer: {
        width: '100%',
        height: '65%',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
    },
    emptyPreviewContainer: {
        width: '90%',
        aspectRatio: 1,
        borderRadius: 12,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    previewImage: {
        width: '90%',
        height: '90%',
        resizeMode: 'cover',
        borderRadius: 12,
    },
    addPhotoButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        width: '80%',
        height: '60%',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#000',
        borderStyle: 'solid',
    },
    addPhotoText: {
        marginTop: 10,
        fontSize: 16,
        fontWeight: '500',
        color: '#000',
    },
    uploadButton: {
        marginTop: 20,
        paddingVertical: 12,
        paddingHorizontal: 30,
        backgroundColor: 'transparent',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#000',
    },
    uploadButtonText: {
        color: '#000',
        fontWeight: '600',
        fontSize: 16,
    },
    changePhotoButton: {
        marginTop: 20,
        paddingVertical: 12,
        paddingHorizontal: 30,
        backgroundColor: 'transparent',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#000',
    },
    changePhotoText: {
        color: '#000',
        fontWeight: '600',
        fontSize: 16,
    },
    navigationContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingBottom: 25,
        paddingHorizontal: 20,
    },
    arrowsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
    },
    arrowButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 15,
        borderRadius: 20,
        backgroundColor: '#e0e0e0',
    },
    activeArrow: {
        backgroundColor: '#f5f5f5',
    },
    removeItemButton: {
        position: 'absolute',
        bottom: 8, 
        alignSelf: 'center', 
        backgroundColor: 'rgba(0, 0, 0, 0.5)', 
        borderRadius: 10,
        padding: 2, 
        width: 20, 
        height: 20, 
        justifyContent: 'center',
        alignItems: 'center',
      },
});